# TODO: Migrate this whole file to pyproject.toml when swithcing to new project structure

exclude = ["vector*"] # TODO: Remove this when vector scripts are passing lint

# Target oldest version of Python used (Python 3.9 for Ubuntu 20.04 LTS)
target-version = "py312"

line-length=250

[lint]
select = [
  "F",    # various basic rules (pyflakes)
  "E",    # errors (pycodestyle)
  "W",    # warnings (pycodestyle)
  "I",    # Import related rules (isort)
  "UP",   # Upgraded version available in newer Python
  "B",    # bugbear rules
  "A",    # shadow builtins
  "EXE",  # Executable file shebangs
  "Q003", # Avoidable escaped quotes
  "Q004", # Unnecessary esacpe character
  "RUF",  # Ruff specific rules
]

ignore = [
  "E501",           # line too long
  "E741",           # ambiguous variable name
  "B007",           # loop control variable not used
  "B9",             # overly opinionated rules
  "RUF005",         # iterable unpacking in list
]
