compiler_exe: /opt/riscv/bin/riscv64-unknown-elf-gcc # executable name on $PATH or full path to executable
ref_model_exe: /opt/riscv/bin/sail_riscv_sim # executable name on $PATH or full path to executable
ref_model_type: sail # sail or spike
udb_config: cvw_config.yaml
linker_script: tests/link.ld
dut_include_dir: tests # Directory containing DUT specific model_test.h header
